[package]
name="atlas-core"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = {workspace=true}
serde = {workspace=true}
thiserror = {workspace=true}
fern = {workspace=true}
chrono = {workspace=true}
log = {workspace=true}
tokio={workspace=true}
env_logger = "0.11.5"
